/* Copyright (c) 2023-2026 MetaCoin-Lab. Licensed under SML-1.0 — see LICENSE.md.
 *
 * TrustLedgerPlugin — the ~45-line Open MCT integration contract, honestly
 * counted: one object provider, one composition provider, one telemetry
 * provider, two types. Read-only over data/trust_ledger.json (generated by
 * generate_view_data.py from the published ledger snapshot). A VIEWER, not
 * a verifier. Open MCT is NASA's open-source mission-control framework
 * (Apache-2.0), used as an npm dependency of this integration only; no NASA
 * affiliation or endorsement. Research-only; no token.
 */
function TrustLedgerPlugin(dataUrl) {
    return function install(openmct) {
        const data = fetch(dataUrl || 'data/trust_ledger.json')
            .then((resp) => resp.json());

        openmct.types.addType('metacoin.events', {
            name: 'Trust-Ledger Event Stream',
            description: 'Anchored audit-log records as mission events',
            cssClass: 'icon-timeline'
        });
        openmct.types.addType('metacoin.metric', {
            name: 'Trust-Ledger Metric',
            description: 'Anchored numeric series (plots)',
            cssClass: 'icon-telemetry'
        });

        openmct.objects.addRoot({ namespace: 'metacoin', key: 'root' });

        openmct.objects.addProvider('metacoin', {
            get: (identifier) => data.then((d) => d.objects[identifier.key])
        });

        openmct.composition.addProvider({
            appliesTo: (domainObject) =>
                domainObject.identifier.namespace === 'metacoin'
                && Array.isArray(domainObject.composition),
            load: (domainObject) => Promise.resolve(domainObject.composition)
        });

        openmct.telemetry.addProvider({
            supportsRequest: (domainObject) =>
                domainObject.type && domainObject.type.startsWith('metacoin.'),
            request: (domainObject, options) => data.then((d) => {
                const rows = d.telemetry[domainObject.identifier.key] || [];
                return rows.filter((r) =>
                    (!options || options.start === undefined
                        || r.utc >= options.start)
                    && (!options || options.end === undefined
                        || r.utc <= options.end));
            })
        });
    };
}
