"""task-0016-triad-attitude — deterministic TRIAD star-tracker attitude determination.

Research-only. A bit-reproducible attitude-determination task: the closed-form TRIAD
algorithm recovers a spacecraft's attitude (the inertial-to-body rotation matrix) from
two reference unit vectors known in the inertial frame — a sun vector and a magnetic
field vector, FIXED constants here — and their body-frame observations. The observations
are GENERATED by a FIXED, KNOWN rotation (axis/angle constants below), so the true
attitude is known exactly and the recovery is checked against ground truth — a
known-truth construction, the same pattern as the Curtis reference case in the Lambert
task (task-0013). It maps to the NASA Technology Taxonomy TX08 (Sensors & Instruments).
The computation is deterministic and reproducible by machine — exactly what MIP-0002
Gate 2 (independent re-run yields a byte-identical hash) checks.

TRIAD (Black, 1964): from primary/secondary vector pairs (s, m) build orthonormal
triads in each frame —
    t1 = s;  t2 = (s x m)/|s x m|;  t3 = t1 x t2
— then R = B_body · B_inertial^T where the B matrices have the triad vectors as
columns. With noise-free, consistent observations (as here), TRIAD is exact up to
floating-point error.

INTERNAL SELF-PROOF (known-truth checks, all BEFORE output rounding):
  (a) orthonormality: max |R·R^T - I| <= 1e-9;
  (b) proper rotation: |det(R) - 1| <= 1e-9 (no reflection);
  (c) observation mapping: max component residual of R·s_inertial - s_body AND
      R·m_inertial - m_body each <= 1e-9 (both exact here because the observations
      are noise-free and mutually consistent — with real sensor noise only the
      primary is honored exactly; that caveat is part of this docstring, not hidden);
  (d) ground-truth recovery: the rotation ANGLE recovered from R (via the trace) and
      the rotation AXIS (via the antisymmetric part) match the known injection
      constants to 1e-6 rad and 1e-9 respectively.
A violated assertion CRASHES the task — stop, don't fudge.

Test-META is a zero-value testnet placeholder and never mints base supply (MIP-0001
paragraph 3, MIP-0002 paragraph 8). Illustrative noise-free geometry (no sensor error
model, no QUEST/Wahba weighting, no star catalog) — NOT a flight attitude system. Not
financial, legal, or flight-engineering advice. No NASA affiliation or endorsement.

Standard library only (math, json, hashlib). No randomness. Every emitted float is
rounded to a fixed number of decimals so re-runs are byte-identical and the SHA-256
output hash is stable (the basis of the Gate-2 check).

Interface is identical to the other tasks so the verifier and agent loop can use them
interchangeably: compute() -> dict, canonical_json(result) -> str, output_hash(result) -> str.
"""

import json
import math

# --- Fixed inputs (part of the reproducibility hash) ------------------------
# Changing any of these changes the canonical output and therefore the Gate-2 hash.
# Reference directions in the inertial frame (normalized in code before use):
SUN_INERTIAL = [1.0, 0.2, 0.1]         # sun sensor line-of-sight (primary vector)
MAG_INERTIAL = [0.3, -0.8, 0.5]        # magnetic field direction (secondary vector)

# The KNOWN injected attitude (ground truth): rotation of ANGLE about AXIS,
# applied as body = R_true · inertial. Axis is normalized in code.
TRUE_AXIS = [1.0, 2.0, 3.0]
TRUE_ANGLE_RAD = 0.6981317007977318    # 40 degrees, exactly math.radians(40)

ORTHONORMALITY_TOL = 1e-9
RESIDUAL_TOL = 1e-9
ANGLE_TOL_RAD = 1e-6
AXIS_TOL = 1e-9
ROUND_DECIMALS = 6


def _norm(v):
    return math.sqrt(sum(c * c for c in v))


def _unit(v):
    n = _norm(v)
    return [c / n for c in v]


def _cross(a, b):
    return [a[1] * b[2] - a[2] * b[1],
            a[2] * b[0] - a[0] * b[2],
            a[0] * b[1] - a[1] * b[0]]


def _mat_vec(m, v):
    return [sum(m[r][c] * v[c] for c in range(3)) for r in range(3)]


def _mat_mul_t(a_cols, b_cols):
    """R = A · B^T where A and B are given as COLUMN triads [t1, t2, t3]."""
    return [[sum(a_cols[k][r] * b_cols[k][c] for k in range(3))
             for c in range(3)] for r in range(3)]


def _rodrigues(axis_unit, angle_rad):
    """Rotation matrix about axis_unit by angle_rad (Rodrigues formula)."""
    x, y, z = axis_unit
    c, s = math.cos(angle_rad), math.sin(angle_rad)
    one_c = 1.0 - c
    return [
        [c + x * x * one_c, x * y * one_c - z * s, x * z * one_c + y * s],
        [y * x * one_c + z * s, c + y * y * one_c, y * z * one_c - x * s],
        [z * x * one_c - y * s, z * y * one_c + x * s, c + z * z * one_c],
    ]


def _triad_basis(primary, secondary):
    """The TRIAD orthonormal basis [t1, t2, t3] for one frame."""
    t1 = _unit(primary)
    t2 = _unit(_cross(primary, secondary))
    t3 = _cross(t1, t2)
    return [t1, t2, t3]


def compute() -> dict:
    """Generate body observations from the known rotation, run TRIAD, self-prove."""
    sun_i = _unit(SUN_INERTIAL)
    mag_i = _unit(MAG_INERTIAL)
    axis = _unit(TRUE_AXIS)
    r_true = _rodrigues(axis, TRUE_ANGLE_RAD)

    # Noise-free body-frame observations from the KNOWN attitude.
    sun_b = _mat_vec(r_true, sun_i)
    mag_b = _mat_vec(r_true, mag_i)

    # --- TRIAD: R maps inertial to body -------------------------------------
    r_triad = _mat_mul_t(_triad_basis(sun_b, mag_b),
                         _triad_basis(sun_i, mag_i))

    # --- INTERNAL SELF-PROOF (stop, don't fudge; all pre-rounding) ----------
    # (a) orthonormality
    ortho_err = max(abs(sum(r_triad[r][k] * r_triad[c][k] for k in range(3))
                        - (1.0 if r == c else 0.0))
                    for r in range(3) for c in range(3))
    assert ortho_err <= ORTHONORMALITY_TOL, f"R not orthonormal: {ortho_err}"
    # (b) proper rotation
    det = (r_triad[0][0] * (r_triad[1][1] * r_triad[2][2]
                            - r_triad[1][2] * r_triad[2][1])
           - r_triad[0][1] * (r_triad[1][0] * r_triad[2][2]
                              - r_triad[1][2] * r_triad[2][0])
           + r_triad[0][2] * (r_triad[1][0] * r_triad[2][1]
                              - r_triad[1][1] * r_triad[2][0]))
    assert abs(det - 1.0) <= ORTHONORMALITY_TOL, f"det(R) = {det}, not +1"
    # (c) both observations mapped exactly (noise-free consistency)
    sun_residual = max(abs(a - b)
                       for a, b in zip(_mat_vec(r_triad, sun_i), sun_b))
    mag_residual = max(abs(a - b)
                       for a, b in zip(_mat_vec(r_triad, mag_i), mag_b))
    assert sun_residual <= RESIDUAL_TOL, f"sun residual {sun_residual}"
    assert mag_residual <= RESIDUAL_TOL, f"mag residual {mag_residual}"
    # (d) ground truth recovered: angle from the trace, axis from the
    # antisymmetric part (valid here: 0 < angle < pi)
    trace = r_triad[0][0] + r_triad[1][1] + r_triad[2][2]
    angle_rec = math.acos(max(-1.0, min(1.0, (trace - 1.0) / 2.0)))
    assert abs(angle_rec - TRUE_ANGLE_RAD) <= ANGLE_TOL_RAD, \
        f"recovered angle {angle_rec} vs true {TRUE_ANGLE_RAD}"
    two_sin = 2.0 * math.sin(angle_rec)
    axis_rec = [(r_triad[2][1] - r_triad[1][2]) / two_sin,
                (r_triad[0][2] - r_triad[2][0]) / two_sin,
                (r_triad[1][0] - r_triad[0][1]) / two_sin]
    axis_err = max(abs(a - b) for a, b in zip(axis_rec, axis))
    assert axis_err <= AXIS_TOL, f"recovered axis off by {axis_err}"

    results = [
        {"quantity": "rotation_matrix_body_from_inertial",
         "value": [[round(v, ROUND_DECIMALS) for v in row]
                   for row in r_triad]},
        {"quantity": "sun_body_unit", "value": [round(v, ROUND_DECIMALS)
                                                for v in sun_b]},
        {"quantity": "mag_body_unit", "value": [round(v, ROUND_DECIMALS)
                                                for v in mag_b]},
    ]

    return {
        "task_id": "task-0016-triad-attitude",
        "inputs": {
            "sun_inertial": list(SUN_INERTIAL),
            "mag_inertial": list(MAG_INERTIAL),
            "true_axis": list(TRUE_AXIS),
            "true_angle_rad": TRUE_ANGLE_RAD,
            "algorithm": "TRIAD (Black 1964), primary = sun vector",
            "round_decimals": ROUND_DECIMALS,
        },
        "results": results,
        "summary": {
            "recovered_angle_deg": round(math.degrees(angle_rec),
                                         ROUND_DECIMALS),
            "recovered_axis_unit": [round(v, ROUND_DECIMALS)
                                    for v in axis_rec],
            "orthonormality_error_max": round(ortho_err, 12),
            "determinant": round(det, ROUND_DECIMALS),
            "sun_mapping_residual_max": round(sun_residual, 12),
            "mag_mapping_residual_max": round(mag_residual, 12),
            "angle_recovery_error_rad": round(abs(angle_rec - TRUE_ANGLE_RAD),
                                              12),
        },
    }


def canonical_json(result: dict) -> str:
    """Serialize the result deterministically.

    sort_keys=True, fixed compact separators, and ensure_ascii=True make the output
    byte-stable across runs and platforms (assuming identical rounded float values).
    """
    return json.dumps(
        result,
        sort_keys=True,
        separators=(",", ":"),
        ensure_ascii=True,
    )


def output_hash(result: dict) -> str:
    """Return the SHA-256 hex digest of the canonical JSON (the Gate-2 reproducibility hash)."""
    import hashlib

    return hashlib.sha256(canonical_json(result).encode("utf-8")).hexdigest()


if __name__ == "__main__":
    _result = compute()
    print(canonical_json(_result))
    print("sha256:" + output_hash(_result))
